function generatePayroll(){

let id=document.getElementById("empId").value;
let name=document.getElementById("empName").value;

let basic=parseFloat(document.getElementById("basicSalary").value);
let allowance=parseFloat(document.getElementById("allowance").value);
let tax=parseFloat(document.getElementById("tax").value);
let deduction=parseFloat(document.getElementById("deduction").value);

if(isNaN(basic) || isNaN(allowance) || isNaN(tax) || isNaN(deduction)){
    alert("Please enter all salary details correctly");
    return;
}

let gross = basic + allowance;
let taxAmount = (gross * tax) / 100;
let net = gross - taxAmount - deduction;

let slip =
"============================\n"+
"      SALARY SLIP\n"+
"============================\n\n"+
"Employee ID : "+id+"\n"+
"Employee Name : "+name+"\n\n"+
"Basic Salary : ₹"+basic+"\n"+
"Allowance : ₹"+allowance+"\n"+
"Gross Salary : ₹"+gross+"\n\n"+
"Tax : ₹"+taxAmount+"\n"+
"Other Deduction : ₹"+deduction+"\n\n"+
"Net Salary : ₹"+net+"\n\n"+
"Generated by Payroll System";

document.getElementById("output").textContent=slip;

}
