function generatePayroll() {

    let id = document.getElementById("empId").value
    let name = document.getElementById("empName").value
    let basic = parseFloat(document.getElementById("basicSalary").value) || 0
    let allowance = parseFloat(document.getElementById("allowance").value) || 0
    let type = document.getElementById("empType").value
    let bonus = parseFloat(document.getElementById("bonus").value) || 0
    let overtime = parseFloat(document.getElementById("overtime").value) || 0
    let tax = parseFloat(document.getElementById("tax").value) || 0
    let deduction = parseFloat(document.getElementById("deduction").value) || 0

    let gross

    if (type === "Manager") {
        gross = basic + allowance + bonus
    } else {
        gross = basic + allowance + overtime
    }

    let taxAmount = gross * (tax / 100)
    let net = gross - taxAmount - deduction

    let slip = `
==============================
        SALARY SLIP
==============================

Employee ID : ${id}
Employee Name : ${name}
Employee Type : ${type}

Basic Salary : ₹${basic}
Allowance : ₹${allowance}

Gross Salary : ₹${gross}

Tax : ₹${taxAmount}
Other Deduction : ₹${deduction}

------------------------------
Net Salary : ₹${net}

Generated by Payroll System
`

    document.getElementById("output").textContent = slip
}



function printSlip() {
    window.print()
}



function exportExcel() {

    let id = document.getElementById("empId").value
    let name = document.getElementById("empName").value
    let basic = document.getElementById("basicSalary").value
    let allowance = document.getElementById("allowance").value
    let type = document.getElementById("empType").value
    let bonus = document.getElementById("bonus").value
    let overtime = document.getElementById("overtime").value
    let tax = document.getElementById("tax").value
    let deduction = document.getElementById("deduction").value

    let gross

    if (type === "Manager") {
        gross = Number(basic) + Number(allowance) + Number(bonus)
    } else {
        gross = Number(basic) + Number(allowance) + Number(overtime)
    }

    let taxAmount = gross * (tax / 100)
    let net = gross - taxAmount - deduction

    let csv = "ID,Name,Type,Basic,Allowance,Tax,Deduction,Net Salary\n"

    csv += `${id},${name},${type},${basic},${allowance},${tax},${deduction},${net}`

    let blob = new Blob([csv], { type: "text/csv" })
    let url = window.URL.createObjectURL(blob)

    let a = document.createElement("a")
    a.href = url
    a.download = "payroll.csv"
    a.click()
}



function showDashboard() {

    let basic = parseFloat(document.getElementById("basicSalary").value) || 0
    let allowance = parseFloat(document.getElementById("allowance").value) || 0
    let tax = parseFloat(document.getElementById("tax").value) || 0

    let gross = basic + allowance
    let taxAmount = gross * (tax / 100)

    alert(
        "Payroll Dashboard\n\n" +
        "Gross Salary: ₹" + gross + "\n" +
        "Tax Amount: ₹" + taxAmount
    )

}



function clearFields() {

    document.getElementById("empId").value = ""
    document.getElementById("empName").value = ""
    document.getElementById("basicSalary").value = ""
    document.getElementById("allowance").value = ""
    document.getElementById("bonus").value = ""
    document.getElementById("overtime").value = ""
    document.getElementById("tax").value = ""
    document.getElementById("deduction").value = ""

    document.getElementById("output").textContent = ""

}



function exitPage() {
    alert("Close the browser tab to exit the application.")
}