function generate() {

    let id = document.getElementById("id").value;
    let name = document.getElementById("name").value;

    let basic = parseFloat(document.getElementById("basic").value);
    let allowance = parseFloat(document.getElementById("allowance").value);
    let tax = parseFloat(document.getElementById("tax").value);
    let deduction = parseFloat(document.getElementById("deduction").value);

    let gross = basic + allowance;

    let taxAmount = (gross * tax) / 100;

    let net = gross - taxAmount - deduction;

    let slip =
        "========== SALARY SLIP ==========\n\n" +
        "Employee ID : " + id + "\n" +
        "Employee Name : " + name + "\n\n" +
        "Basic Salary : " + basic + "\n" +
        "Allowance : " + allowance + "\n" +
        "Gross Salary : " + gross + "\n\n" +
        "Tax : " + taxAmount + "\n" +
        "Deduction : " + deduction + "\n\n" +
        "Net Salary : " + net + "\n\n" +
        "Generated by Payroll System";

    document.getElementById("result").textContent = slip;

}